<?php
require __DIR__ . '/apa_log.admin.inc';
/**
 * Implements hook_permission().
 */
function apa_log_permission()
{
  //setting module permissions
  return [
    'access member_log settings' => [
      'title' => t('access member log settings'),
      'description' => t('Access Member Log Settings'),
    ],
  ];
}
/**
 * Implements hook_menu().
 */
function apa_log_menu() {
  // A path where all Global config lives.
  $items['admin/config/system/memberlog'] = array(
    'title' => 'APA Member Transaction Error Log',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('apa_log_admin_settings'),
    'access arguments' => array('access member_log settings'),
    //'access callback' => TRUE,
    'type' => MENU_LOCAL_ACTION | MENU_NORMAL_ITEM,
    
  );
  return $items;
}
/*
* Create submit function to get the value
*/
function log_submit($form, &$form_state) {
  //$form_state['storage']['type'] = $form_state['values']['type'];
  $filterConditions =  array();
  $filterConditions["beginDate"] = $form_state['values']['beginDate'];
  $filterConditions["endDate"] = $form_state['values']['endDate'];
  if(!empty($form_state['values']['email'])) { $filterConditions["email"] = $form_state['values']['email']; }
  $filterConditions["type"] = $form_state['values']['type'];
  $filterConditions["error"] = $form_state['values']['error'];
  $form_state['rebuild'] = TRUE; 
  drupal_session_start();
  if( $form_state['values']['type'] == "ALL") {
    $_SESSION["GetAll"] = 1;
  }else{
    unset($_SESSION["GetAll"]);
  }
  if( $form_state['values']['error'] == "ALL") {
    $_SESSION["AllError"] = 1;
  }else{
    unset($_SESSION["AllError"]);
  }
  $_SESSION["filterconditions"] = $filterConditions;
}
/*
* Show all data from member_log table
*/
function log_all($form, &$form_state) {
   drupal_session_start();
   $_SESSION["GetAll"] = 1;
   $form_state['rebuild'] = TRUE; 
   unset($_SESSION["filterconditions"]); 
  
}
/*
* Clear the session
*/
function clear_all($form, &$form_state) {
  if(isset($_SESSION["filterconditions"])) {  unset($_SESSION["filterconditions"]); }
  if(isset($_SESSION["GetAll"] )) {  unset($_SESSION["GetAll"] ); }
  if(isset($_SESSION["AllError"] )) {  unset($_SESSION["AllError"] ); }
 
}
/*
* Create log data for the member's transactions
*/
function add_Member_Log($addMemberLog) {
  $userID = $addMemberLog["userID"];
	$orderID = $addMemberLog["orderID"];
	$jsonMessage = $addMemberLog["jsonMessage"];
	$createDate = $addMemberLog["createDate"];
	$type = $addMemberLog["type"];
  $logError = $addMemberLog["logError"];
  $timeStamp = strtotime(date('Y-m-d H:i:s'));
  $memberLog	=  db_insert('member_log') 
    ->fields(array(
      'UserID' => $userID,
      'OrderID' => $orderID,
      'JsonMessage' => $jsonMessage,
      'CreateDate' => $createDate,
      'Type' => $type,
      'LogError' => $logError,
      'TimeStamp' => $timeStamp,
    ))
    ->execute();
 
}
/*
* Export the data
*/
function export_all($form, &$form_state) {
  $query = db_select('member_log','m');
  $query ->fields('m', array('UserID','OrderID', 'JsonMessage', 'TimeStamp', 'Type', 'LogError','CreateDate'));
  // handle display all data
  if(isset($_SESSION['filterconditions']["email"])) {$query->condition('UserID', $_SESSION['filterconditions']["email"]); }
  if(!isset($_SESSION["GetAll"])) {$query->condition('Type', $type); }
  if(isset($_SESSION['filterconditions']["beginDate"]) && isset($_SESSION['filterconditions']["endDate"])) { 
  $query->condition('CreateDate', array($_SESSION['filterconditions']["beginDate"], $_SESSION['filterconditions']["endDate"]), 'BETWEEN'); }
  if(!isset($_SESSION["AllError"])) {if(isset($_SESSION['filterconditions']["error"])) {$query->condition('LogError', $_SESSION['filterconditions']["error"]); }}
  $query->orderBy('CreateDate', 'DESC');
  $query->orderBy('TimeStamp', 'DESC');
  $queryResult = $query->execute();
  $arrayReturn = array();
  while ($row = $queryResult->fetchAssoc()) {$arrayReturn[] = $row;  }  
    $arrayResult = array();
  if(sizeof($arrayReturn)!= 0){
      foreach($arrayReturn as $singleArr){
        $tempResult = array();
        $tempResult['UserID'] = $singleArr['UserID'];
        $tempResult['OrderID'] = $singleArr['OrderID'];
        $tempResult['JsonMessage'] = $singleArr['JsonMessage'];
        $tempResult['TimeStamp'] = date('Y-m-d H:i:s',$singleArr['TimeStamp']);
        $tempResult['Type'] = $singleArr['Type'];
        $tempResult['LogError'] = $singleArr['LogError'];
        $tempResult['CreateDate'] = $singleArr['CreateDate'];
        array_push($arrayResult, $tempResult);
      }
  }
  drupal_add_http_header('Content-Type', 'text/csv');
  drupal_add_http_header('Content-Disposition', 'attachment; filename=member_transaction.csv');
  $csvdata = 'UserID,OrderID,Message,DateTime,Type,Error,Date' . PHP_EOL;
  foreach ($arrayResult as $record) {
    $row = array();
    $row[] = $record['UserID']; 
    $row[] = $record['OrderID'];
    $row[] = str_replace("<br/><br/>", "    ",str_replace(",", " ",$record['JsonMessage'])); 
    $row[] = $record['TimeStamp']; 
    $row[] = $record['Type']; 
    $row[] = $record['LogError'];
    $row[] = $record['CreateDate'];
    $csvdata .= implode("," , $row). PHP_EOL;
 }
  print $csvdata;
  drupal_exit();
 
}