<?php

/**
 * @file
 * Aptify API Module.
 * This module will be responsible to communicate with Aptify.
 * The reason for moving the code to the module is it will provide with better perfomance and decoupled methods.
 */


require __DIR__ . '/aptify_api.admin.inc';
require __DIR__ . '/classes/AptifyFailure.php';

/**
 * Constant to identify log messages in Drupal DB Log.
 */
define('APTIFY_API_WATCHDOG', 'Aptify');

/**
 * Implements hook_menu().
 */
function aptify_api_menu() {
  // A path where all Global config lives.
  $items['admin/config/system/aptifyapi'] = array(
    'title' => 'Aptify API',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('aptify_api_admin_settings'),
    'type' => MENU_LOCAL_ACTION | MENU_NORMAL_ITEM,
    'access arguments' => array('administer site configuration'),
    'file' => 'aptify_api.admin.inc',
  );


  // This is test page corresponds to aptify_test_calls_logged_in() function to test the calls.
  // This will only work if debug-mode is on
    global $debug_mode;
    if($debug_mode) {
        $items['apa/test-api'] = [
            'title' => "apa SSO Test",
            'page callback' => 'aptify_test_calls_logged_in',
            'page arguments' => [],
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        ];
    }

  return $items;
}

/**
 * Initial function to get token and login user for further communication.
 * If successful all the values will be set to the session.
 *  This is same as calling Case#7 as of AptifyAPI
 * @param $email_address
 * @param $password
 * @return boolean
 * @throws AptifyFailure
 */
function aptify_api_login($email_address, $password) {
  $base_url = variable_get('aptify_api_base_url', APTIFY_API_BASE_URL_DEFAULT);

  $parameters = [
      'UserName' => $email_address,
      'Password' => $password
  ];

  // This step is important as it filters out any malicious code.
  $query = drupal_http_build_query($parameters);

  $login_path = "/Authentication/Login/Web?".$query;

    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $base_url . $login_path);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    $headers = array();
    $headers[] = "Content-Type: application/json";
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    $result = curl_exec($ch);
    $response_status_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);

    if (curl_errno($ch)) {
        $message_detail = 'Error:' . curl_error($ch);
        //throw new AptifyFailure($message_detail);
    }

    curl_close ($ch);
    // Request authentication and HTTP response check.
    //$response = drupal_http_request($base_url . $login_path, $options);
    if ($response_status_code != 200) {
        watchdog(APTIFY_API_WATCHDOG, $result, array(), WATCHDOG_CRITICAL);
        //throw new AptifyFailure("Communication Error.\nError Code : {$response_status_code}");
    }

    $response = new stdClass();
    $response->data = $result;

  // Response decode and decode check.
  $r = drupal_json_decode($response->data);
  if ($r === NULL) {
    $message_detail = 'JSON decode failure: ' . $response->data;
    watchdog(APTIFY_API_WATCHDOG, $message_detail, array(), WATCHDOG_CRITICAL);
    //throw new AptifyFailure($message_detail);
  }

  // Aptify response status.
  if (isset($r['ErrorInfo']) === TRUE) {
    $message_detail = 'aptify error detected: ';// . $r['ErrorInfo']->ErrorMessage;
    watchdog(APTIFY_API_WATCHDOG, $message_detail, array(), WATCHDOG_INFO);
	$_SESSION["loginFail"] = 1;
    //throw new AptifyFailure($r['ErrorInfo'], $r['extra_info']);
  }
  else {
      if (!($r['UserId'] || $r['TokenId'])) {
          $message_detail = 'No UserId or Token found.';
          watchdog(APTIFY_API_WATCHDOG, $message_detail, array(), WATCHDOG_INFO);
          //throw new AptifyFailure($message_detail, $r);
      }

      // If all okay we will  set data to the session.
      $_SESSION['Log-in'] = "in";
      foreach($r as $key=>$value) {
          $_SESSION[$key] = $value;
      }
    //return TRUE;
	return $r;
  }
}

/**
 * A function to get key from session.
 * The session is setup when user is logged in.
 * @param $key
 * @return mixed
 */
function _aptify_get($key){
  if(isset($_SESSION[$key])) {
		return $_SESSION[$key];
	}
}

/**
 * Function to test out functionality and API Calls.
 */
function aptify_test_calls_logged_in(){
    $return = NULL;
    $return = aptify_get_member_details();
     drupal_json_output($return);
}

/**
 * This is the main method makes call to APTIFY api.
 * Very similar to curlRequest function.
 * Each API function should use this function as central call.
 * @param $api_number string name to identify the call.
 * @param $path string "Must start with / (ForwardSlash)"
 * @param $token string
 * @param $data  mixed (Can be used as query for GET Parameters)
 * @param string $method
 * @return mixed
 * @throws AptifyFailure
 */
function _aptify_api_call($api_number, $path, $token, $data, $method = 'GET') {
    $base_url = variable_get('aptify_api_base_url', APTIFY_API_BASE_URL_DEFAULT);

    $ch = curl_init();
    $headers = array();

    if ($token) {
        $headers[]="AptifyAuthorization: Web ".$token;
    }

    if($method == "Image" || $method == "Order" || $method == "JSON") {
        $headers[] = "Content-Type:application/json";
    } elseif($method == "Secure" || $method == "SecureNoToken") {
        $headers[] = "Content-Type:application/x-www-form-urlencoded";
    } elseif($method == "JSON") {
        $headers[] = "Content-Type:application/json";
    } elseif($method == "PDF") {
        $headers[] = "AptifyAuthorization: DomainWithContainer ".$data;
    } elseif($method == "GetPost") {
        $headers[] = 'Content-Length: 0';
    }
    //$headers[] = "Content-Type:application/json";
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    /*
    if($method === 'POST') {
        $request_data = drupal_json_encode($data);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $request_data);
        curl_setopt($ch, CURLOPT_POST, TRUE);
    }

    if($method === 'PUT') {
        $request_data = drupal_json_encode($data);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $request_data);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
    }*/

    if($method == "JSON"||$method == "Image"|| $method == "Order") {
		if(!empty($data) || $data != null) {
			curl_setopt($ch, CURLOPT_POST, 1);
			curl_setopt($ch, CURLOPT_POSTFIELDS,$data);
		}
    } elseif($method == "Secure" || $method == "SecureNoToken") {
		if(!empty($data) || $data != null) {
			$secureData = http_build_query($data);
			curl_setopt($ch, CURLOPT_POST, 1);
			curl_setopt($ch, CURLOPT_POSTFIELDS,$secureData);
		}
	} elseif($method == "GetPost") {
		curl_setopt($ch, CURLOPT_POST, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode(array()));
	} elseif($method == "PDF") {
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
	}

    /** @todo : Add custom calls i.e, "GetPost" from AptifyAPI.php */

    // URL.
    $request_url = $base_url . $path;
    if (!empty($data)) {
        if($method === 'GET' || $method === 'GetPost') {
            $request_url .= $data;
            //$request_url .= '?' . http_build_query($
            if($method === 'GET') { curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET"); }
        }
    }
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
    curl_setopt($ch, CURLOPT_URL, $request_url);
    curl_setopt($ch, CURLOPT_BINARYTRANSFER,1);
	curl_setopt($ch, CURLOPT_ENCODING, "");
	curl_setopt($ch, CURLOPT_MAXREDIRS, 10);
	curl_setopt($ch, CURLOPT_TIMEOUT, 30);
	curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
    // todo! You must do this before go live!
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

    $result = curl_exec($ch);

    $response_status_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);

    if (curl_errno($ch)) {
        $message_detail = 'Error:' . curl_error($ch);
        //throw new AptifyFailure($message_detail);
        return curl_error($ch);
    }

    curl_close ($ch);
    // Request authentication and HTTP response check.
    //$response = drupal_http_request($base_url . $login_path, $options);
    if ($response_status_code != 200) {
		if($response_status_code != 201) {
			$message = "There is a problem at <strong>!request_url</strong><br/>";

			$message .= "Response came is  was <pre>!response</pre><br/>";
			$replacements = [
				'!request_url' => $method."//".$request_url,
				'!response' => $result,
			];
			if(isset($request_data)) {
				$replacements['!data'] = var_dump($request_data);
				$message .= "The data sent was <pre>!data</pre><br/>";
			}
			watchdog(APTIFY_API_WATCHDOG, $message, $replacements, WATCHDOG_CRITICAL,$request_url);
			//throw new AptifyFailure("Communication Error.\nError Code : {$response_status_code}");
		}
    }

    // Request authentication and HTTP response check.
    $response = new stdClass();
    $response->data = $result;

    // if debugging is on
    $data_sent = isset($request_data) ? $request_data : "No data was sent.";
    aptify_log_to_watchdog($api_number, $request_url, $data_sent, $response);

    // Response decode and decode check.
    if($api_number == '28. PD - Get event search result list' || $api_number == '29. PD - Get event detail' || $api_number == '30. PD - Get event detail list' || $api_number == '4. Dashboard - Get member detail') {
        $r = json_clean_decode($result, true);
    } elseif($api_number == '8. Dashboard - Log-out') {
        $r = "";
    } else {
        $r = drupal_json_decode($response->data);
    }
    if ($r === NULL) {
        $message_detail = $api_number . ' JSON decode failure: ' . $response->data;
        watchdog(APTIFY_API_WATCHDOG, $message_detail, array(), WATCHDOG_CRITICAL);
        //throw new AptifyFailure($message_detail);
        return $r;
    }
    // Aptify response status.
    if (isset($r['ErrorInfo']) === TRUE) {
        $message_detail = 'aptify error detected: ' . $r['ErrorInfo']->ErrorMessage;
        watchdog(APTIFY_API_WATCHDOG, $message_detail, array(), WATCHDOG_INFO);
        //throw new AptifyFailure($r['ErrorInfo'], $r['extra_info']);
        return $r;
    }
    else {
        return $r;
    }
}

/***********************************************************************************************
 * All the AptifyCalls goes below:
/***********************************************************************************************

/**
 * Function to return member details.
 * @return mixed
 * @throws AptifyFailure
 */
function aptify_get_member_details() {
  $path = "/GetDBMemberDetails";
  $data = ['UserId' => _aptify_get('UserId')];
  return _aptify_api_call("4",$path, _aptify_get('TokenId'), $data);
}

/**
 * Get renewal Quatation OrderID
 * @return mixed
 * @throws AptifyFailure
 */
function aptify_get_renewal_quotation_order_id() {
    $path = "/DataObjects/spGetQuatationOrderID__c";
    $data = ['UserId' => _aptify_get('UserId')];
    return _aptify_api_call("45",$path, _aptify_get('TokenId'), $data);
}

/**
 * Returns event HTML based on data sent to function
 * @param array $data
 * $data requires requires Latitude,Longtitude,Radius,Keyword,Typeofpd,Nationalgp,Regionalgp,State,Suburb,BeginDate,Endate,PageSize,PageNumber
 * @return mixed
 * @throws AptifyFailure
 */
function aptify_get_event_search_result(array $data) {
    $path = "/PDGetEventSearchResultsList";
    return _aptify_api_call("28",$path, _aptify_get('TokenId'), $data);
}



/**
 * Call every APIs' url here
 * -Eddy-
 */
function aptify_get_GetAptifyData($TypeAPI, $ArrayIn) {
	// Array to JSON
	$arrayToJson = drupal_json_encode($ArrayIn);
	// pass array and JSON version together and use them as needed.
    $jsonreturn = aptify_get_url_by_number($TypeAPI, $ArrayIn, $arrayToJson);
    /*
    ?>
    <?php if($TypeAPI == "22") {var_dump($jsonreturn);} ?>
    <?php
    */
    return $jsonreturn;
}

function aptify_get_url_by_number($APItype, $variables, $jsonVersion) {
    switch($APItype){
        case "0":
            // JSON persar
            // Eddy - done check;
            //echo "<br />1. Dashboard Main: <br />";
            $API = "/services/DataObjects/spGetMemberDetailsForSSO__c?";
            $passInput = "Userid=".$variables;
            $APIreturn = $API. $passInput;
            array_push($outputReturn, $JSONreturn);
            array_push($outputReturn, "0. SSO details Endpoint");
            return $outputReturn;
            //return "Test! 0 in";
        case "1":
            // Eddy - done check;
            //echo "<br />1. Dashboard Main: <br />";
            $API = "/DataObjects/spGetDashboardMainDetailsForUserID__c?";
            $passInput = "Userid=".$variables;
            //return $outputReturn;
            return _aptify_api_call("1. Dashboard Main",$API, _aptify_get('TokenId'), $passInput);
        case "2":
            // Eddy - done check;
            //echo "<br />2. Get membership Certificate PDF: <br />";
            $AptifyAuth = 'https://aptifyweb.australian.physio/AptifyServicesAPI/services/Authentication/Login/DomainWithContainer?UserName=appsvruser&Password=R#D8_Hn@4p';
            $AuthToken = curlRequest($AptifyAuth, "Get", "");
            $AuthToken = json_decode($AuthToken, true);
            $AuthToken = $AuthToken["TokenId"];

            $API = "https://aptifyweb.australian.physio/AptifyServicesAPI/forms/CrystalReportView.aspx?ViewMode=entityRecord&ViewEntityName=Persons&ReportId=151&";
            $passInput = "EntityRecordID=".$variables."&AptifyAuthorization=DomainWithContainer%20".$AuthToken;
            $API = $API.$passInput;
            $APItt = "https://aptifyweb.australian.physio/AptifyServicesAPI/forms/CrystalReportView.aspx?ViewMode=entityRecord&ViewEntityName=Persons&ReportId=150&";
            $passInputt = "EntityRecordID=".$variables."&AptifyAuthorization=DomainWithContainer%20".$AuthToken;
            $APItt = $APItt.$passInput;
            $APIs["M"] = $API;
            $APIs["I"] = $APItt;
            return $APIs;
        case "3":
            // Eddy - done check;
            //echo "<br />3. Get membership insurance certificate PDF: <br />";
            $AptifyAuth = 'https://aptifyweb.australian.physio/AptifyServicesAPI/services/Authentication/Login/DomainWithContainer?UserName=appsvruser&Password=R#D8_Hn@4p';
            $AuthToken = curlRequest($AptifyAuth, "Get", "");
            $AuthToken = json_decode($AuthToken, true);
            $AuthToken = $AuthToken["TokenId"];
            $API = "https://aptifyweb.australian.physio/AptifyServicesAPI/forms/CrystalReportView.aspx?ViewMode=entityRecord&ViewEntityName=Persons&ReportId=150&";
            $passInput = "EntityRecordID=".$variables."&AptifyAuthorization=DomainWithContainer%20".$AuthToken;
            $API = $API.$passInput;
            $JSONreturn = curlRequest($API, "PDF", $AuthToken);
            return $API;
        case "4":
            //API test by JingHu
            //echo "<br />4. Dashboard - Get member detail: <br />";
            $API = "/GetDBMemberDetails?";		
            return _aptify_api_call("4. Dashboard - Get member detail",$API, _aptify_get('TokenId'), $variables);
            break;
        case "5":
            //API test by JingHu
            //echo "<br />5. Member detail - Update: <br />";
            $API = "/DMemberDetailUpdate";
            return _aptify_api_call("5. Member detail - Update",$API, _aptify_get('TokenId'), $jsonVersion,"JSON");
            break;
        case "6":
            // Eddy;
            //echo "<br />6. Dashboard - Forgot password: <br />";
            if(isset($variables["Token"])) {
                $API = "/Authentication/PasswordReset/Web";
                return _aptify_api_call("6. Dashboard - Forgot password",$API, _aptify_get('TokenId'), $variables,"SecureNoTokenJSON");
            } else {
                $API = "/Authentication/PasswordResetRequest/Web?";
                $variable = "UserName=".$variables["email"]."&email=".$variables["email"];
                return _aptify_api_call("6. Dashboard - Forgot password",$API, _aptify_get('TokenId'), $variable,"GetPost");
            }
        case "7":
            // Eddy - done check;
            //echo "<br />7. Dashboard - log-in: <br />";
            $API = "https://aptifyweb.australian.physio/AptifyServicesAPI/services/Authentication/Login/Web?";
            $variable = "UserName=".$variables['ID']."&Password=".$variables['Password'];
            $JSONreturn = curlRequest($API, "Get", $variable);
            array_push($outputReturn, $JSONreturn);
            array_push($outputReturn, "7. Dashboard - log-in");
            return $outputReturn;
        case "8":
            // Eddy - done check;
            //echo "<br />8. Dashboard - Log-out: <br />";
            $API = "/Authentication/Logout";
            return _aptify_api_call("8. Dashboard - Log-out",$API, _aptify_get('TokenId'),"", "t");
        case "9":
            // Eddy - done check;
            //echo "<br />9. Dashboard - change password: <br />";
            $API = "/UpdatePassword";
            return _aptify_api_call("9. Dashboard - change password",$API, _aptify_get('TokenId'),$jsonVersion, "JSON");
        case "10":
            //API test by JingHu
            //echo "<br />10. Dashboard - Get picture: <br />";
            $PersonID = $_SESSION['LinkId'];
            $API = "/ImageField/Persons/".$PersonID."/Photo";
            return _aptify_api_call("10. Dashboard - Get picture",$API, _aptify_get('TokenId'),"");
            break;
        case "11":
            //API test by JingHu
            //echo "<br />11. Dashboard - Update picture: <br />";
            $API = "/GenericEntity/SaveData";
            return _aptify_api_call("11. Dashboard - Update picture",$API, _aptify_get('TokenId'), $jsonVersion,"Image");
            break;
        case "12":
            //API test by JingHu
            $API = "/DataObjects/spGetPaymentListing__c?";
            //echo "<br />12. Dashboard - Get payment listing: <br />";
            $data = "UserID=".$variables["id"];
            return _aptify_api_call("12. Dashboard - Get payment listing",$API, _aptify_get('TokenId'),$data);
            break;
        case "13":
            //API test by JingHu
            //echo "<br />13. Dashboard - update payment method: <br />";
            $API = "/ProcessFlow/UpdatePaymentMethod__c?";
            return _aptify_api_call("13. Dashboard - update payment method",$API, _aptify_get('TokenId'),$variables, "Secure");
            break;
        case "14":
            // Merged together with Case 13
            //echo "<br />14. Delete payment method: <br />";
            $JSONreturn = "";
            array_push($outputReturn, $JSONreturn);
            array_push($outputReturn, "14. Delete payment method");
            return $outputReturn;
        case "15":
            //API test by JingHu
            //echo "<br />15. Dashboard - Add payment method: <br />";
            $API = "/AddPaymentMethod";
            return _aptify_api_call("15. Dashboard - Add payment method",$API, _aptify_get('TokenId'),$jsonVersion, "JSON");
            break;
        case "16":
            //API test by JingHu
            //echo "<br />16. Dashboard - Check existing email: <br />";
            $API = "https://aptifyweb.australian.physio/AptifyServicesAPI/services/VerifyUserName/".$variables["ID"];
            $JSONreturn = curlRequest($API, "JSON",""); 
            array_push($outputReturn, $JSONreturn);
            array_push($outputReturn, "16. Dashboard - Check existing email");
            return $outputReturn;
        case "17":
            // Eddy - done check;
            //echo "<br />17. Dashboard - Get payment history list: <br />";
            $API = "/GetOrderDetails?";
            $sent = "UserID=".$variables["ID"];
            return _aptify_api_call("17. Dashboard - Get payment history list",$API, _aptify_get('TokenId'),$sent);
        case "18":
            // Eddy
            //echo "// 18. Get payment invoice PDF: <br />";
            $AptifyAuth = 'https://aptifyweb.australian.physio/AptifyServicesAPI/services/Authentication/Login/DomainWithContainer?UserName=appsvruser&Password=R#D8_Hn@4p';
            $AuthToken = curlRequest($AptifyAuth, "Get", "");
            $AuthToken = json_decode($AuthToken, true);
            $AuthToken = $AuthToken["TokenId"];
            $returnArr = Array();
            foreach($variables as $var) {
                $API = "https://aptifyweb.australian.physio/AptifyServicesAPI/forms/CrystalReportView.aspx?ViewMode=entityRecord&ViewEntityName=Orders&ReportId=154&";
                $passInput = "EntityRecordID=".$var."&AptifyAuthorization=DomainWithContainer%20".$AuthToken;
                $API = $API.$passInput;
                array_push($returnArr, $API);
            }
            return $returnArr;
        case "19":
            // Eddy - done check;
            //echo "<br />19. Dashbaord - Get list of National Group: <br />";
            $API = "/NationalGroupProducts/";
            $API = $API.$variables["UserID"];
            return _aptify_api_call("19. Dashbaord - Get list of National Group",$API, _aptify_get('TokenId'),$jsonVersion,"JSON");
        case "20":
            // Eddy - done check;
            //echo "<br />20. Dashboard - Get list of subscribed National Group: <br />";
            $API = "/DataObjects/spGetListOfSubscribedNationalGroup__c?";
            $var = "UserID=".$variables["UserID"];
            $JSONreturn = curlRequest($API, "Get", $var);
            return _aptify_api_call("20. Dashboard - Get list of subscribed National Group",$API, _aptify_get('TokenId'),$var);
        case "21":
            // Eddy - done check;
            //echo "<br />21. Dashboard - Get list of Fellowship Products: <br />";
            $API = "/FellowshipProducts/-1";
            return _aptify_api_call("21. Dashboard - Get list of Fellowship Products",$API, _aptify_get('TokenId'),$jsonVersion,"JSON");
        case "22":
            // Eddy - done check;
            //echo "<br />22. Dashboard - Get list of subscribed Fellowship Product: <br />";
            $API = "/DataObjects/spGetListOfSubscribedFellowshipProducts__c?";
            $var = "UserID=".$variables["UserID"];
            return _aptify_api_call("22. Dashboard - Get list of subscribed Fellowship Product",$API, _aptify_get('TokenId'),$var);
        case "23":
            // Eddy - done check;
            //echo "<br />23. Dashbard - Get list of Subscription preferences: <br />";
            $API = "/DataObjects/spGetListOfSubscriptionPreferences__c?";
            $var = "UserID=".$variables["UserID"];
            return _aptify_api_call("23. Dashbard - Get list of Subscription preferences",$API, _aptify_get('TokenId'),$var);
        case "24":
            // Eddy - done check;
            //echo "<br />24. Dashbaord - Update subscription preferences: <br />";
            $API = "/UpdateSubscriptionPref";
            return _aptify_api_call("24. Dashbaord - Update subscription preferences",$API, _aptify_get('TokenId'),$jsonVersion, "JSON");
        case "25":
            //API test by JingHu
            //echo "<br />25. User Registration: <br />";
            $API = "/UserRegistration";
            return _aptify_api_call("25. User Registration",$API, _aptify_get('TokenId'),$jsonVersion,"JSON");
            break;
        case "26":
            //API test by JingHu
            //echo "<br />26. REgister a new member order: <br />";
            $API = "/PlaceOrder";
            return _aptify_api_call("26. REgister a new member order",$API, _aptify_get('TokenId'),$jsonVersion,"Order");
            break;
        case "27":
            //API test by JingHu
            //echo "<br />27. Renew membership order: <br />";
            $API = "/RenewMembershipOrder";
            return _aptify_api_call("27. Renew membership order",$API, _aptify_get('TokenId'),$jsonVersion,"JSON");
        case "28":
            // Eddy 
            //echo "<br />28. PD - Get event search result list: <br />";
            $API = "/PDGetEventSearchResultsList";
            return _aptify_api_call("28. PD - Get event search result list",$API, _aptify_get('TokenId'),$jsonVersion,"JSON");
        case "29":
            // Eddy 
            //echo "<br />29. PD - Get event detail: <br />";
            $API = "/PDGetEventDetail";
            return _aptify_api_call("29. PD - Get event detail",$API, _aptify_get('TokenId'),$jsonVersion,"JSON");
        case "30":
            // Eddy 
            //echo "<br />30. PD - Get event detail list: <br />";
            $API = "/PDGetEventDetailList";
            return _aptify_api_call("30. PD - Get event detail list",$API, _aptify_get('TokenId'),$jsonVersion,"JSON");
        case "31":
            //API test by JingHu
            //echo "<br />31. Get Membership product price: <br />";
            //$API = "https://aptifyweb.australian.physio/AptifyServicesAPI/services/MembershipProducts/".$_SESSION['UserId'];
            if(isset($_SESSION['UserId'])){
                $API = "/MembershipProducts/".$_SESSION['UserId'];}
            else{
                $API = "/MembershipProducts/-1";	
            }
            //$JSONreturn = curlRequest($API, "JSON", $jsonVersion); 
            return _aptify_api_call("31. Get MEmbership product price",$API, _aptify_get('TokenId'),$jsonVersion,"JSON");
        case "32":
            //echo "<br />32. Order confirmation: <br />";
            // For the actual API use - user User registration instead
            $JSONreturn = '{
                "Orderstatus":"done!",
                "InvoiceID":"12"
            }';
            array_push($outputReturn, $JSONreturn);
            array_push($outputReturn, "32. Order confirmation");
            return $outputReturn;
        case "33":
            // Eddy - done check;
            //echo "<br />33. Get CPD diary: <br />";
            $API = "/GetEducationUnits__c/";
            return _aptify_api_call("33. Get CPD diary",$API, _aptify_get('TokenId'),$variables);
        case "34":
            // Eddy - done check;
            //echo "<br />34. Insert CPD diary: <br />";
            $API = "/CreateNonAPAEducationUnits";
            return _aptify_api_call("34. Insert CPD diary",$API, _aptify_get('TokenId'),$jsonVersion, "JSON");
        case "35":
            // Eddy
            // echo "<br />35. Find a Physio data: <br />";
            // cron.
            $JSONreturn = "";
            return $JSONreturn;
        case "36":
            //API test by JingHu
            //echo "<br />36. Get workplace settings list <br />";
            $API = "https://aptifyweb.australian.physio/AptifyServicesAPI/services/DataObjects/spGetWorkPlaceSettings__c";
            $JSONreturn = curlRequest($API, "Get", "");
            array_push($outputReturn, $JSONreturn);
            array_push($outputReturn, "36. Get workplace settings list ");
            return $outputReturn;
        case "37":
            // Merged to 39
            //echo "<br />37. Get special interest area list <br />";
            $JSONreturn = "";
            return $JSONreturn;
        case "38":
            // Eddy
            //echo "<br />38. Get NON-APA CPD point's PDF<br />";
            $AptifyAuth = 'https://aptifyweb.australian.physio/AptifyServicesAPI/services/Authentication/Login/DomainWithContainer?UserName=appsvruser&Password=R#D8_Hn@4p';
            $AuthToken = curlRequest($AptifyAuth, "Get", "");
            $AuthToken = json_decode($AuthToken, true);
            $AuthToken = $AuthToken["TokenId"];
            $API = "https://aptifyweb.australian.physio/AptifyServicesAPI/forms/CrystalReportView.aspx?ViewMode=entityRecord&ViewEntityName=Persons&ReportId=152&";
            $passInput = "EntityRecordID=".$variables."&AptifyAuthorization=DomainWithContainer%20".$AuthToken;
            $API = $API.$passInput;
            return $API;
        case "39":
            // For the actual API use
            //echo "<br />39. Get dropdown option list: <br />";
            $API = "https://aptifyweb.australian.physio/AptifyServicesAPI/services/GetOptionValues";		
            $JSONreturn = curlRequest($API, "", "Get");
            array_push($outputReturn, $JSONreturn);
            array_push($outputReturn, "39. Get dropdown option list");
            return $outputReturn;
        case "40":
            // test by Jing Hu
            //echo "<br />40. Get Insurance Data: <br />";
            $API = "/DataObjects/spGetPersonInsuranceData__c?";
            $insuranceData ="UserID=".$variables["ID"];
            return _aptify_api_call("40. Get Insurance Data",$API, _aptify_get('TokenId'),$insuranceData);
        case "41":
            // test by Jing Hu
            //echo "<br />41. Save Insurance Data: <br />";
            $API = "/GenericEntity/SaveData";
            return _aptify_api_call("41. Save Insurance Data",$API, _aptify_get('TokenId'),$jsonVersion,"JSON");
        case "42":
            // test by Jing Hu
            //echo "<br />42. Sign up: <br />";
            $API = "/CreateWebUser";
            return _aptify_api_call("42. Sign up",$API, _aptify_get('TokenId'),$jsonVersion,"JSON");
        case "43":
            // test by Jing Hu
            //echo "<br />43. Get installment details for the user: <br />";
            $API = "/DataObjects/spGetUserInstallmentDetails__c?";
            $data = "UserID=".$variables["id"];
            return _aptify_api_call("43. Get installment details for the user",$API, _aptify_get('TokenId'),$data);
        case "44":
            // test by Jing Hu
            //echo "<br />44. Get Order Details <br />";
            $API = "/OrderDetails/";
            $JSONreturn = curlRequest($API, "Get", $variables);	
            return _aptify_api_call("44. Get Order Details",$API, _aptify_get('TokenId'),$variables);
        case "45":
            // test by Jing Hu
            //echo "<br />45. Get Renewal Quatation OrderID <br />";
            $API = "/DataObjects/spGetQuatationOrderID__c?";
            $data = "UserID=".$variables["id"];
            return _aptify_api_call("45. Get Renewal Quatation OrderID",$API, _aptify_get('TokenId'),$data);
        case "46":
            // test by Jing Hu
            //echo "<br />46. Get Order payment schedules <br />";
            $API = "/DataObjects/spGetOrderPaymentScheduledDetails__c?";
            $data = "OrderID=".$variables["id"];
            return _aptify_api_call("46. Get Order payment schedules ",$API, _aptify_get('TokenId'),$data);
        case "47":
            // test by Jing Hu
            //echo "<br />47. Get calculating the Order Total and Schedule Payments <br />";
            $API = "/GetOrderPaymentDetail";
            return _aptify_api_call("47. Get calculating the Order Total and Schedule Payments ",$API, _aptify_get('TokenId'),$jsonVersion,"JSON");
    }
}
/**
 * Helper function to log values in Drupal's Watchdog (DBlog)
 * It will only work if Debug mode is on at admin/config/system/aptifyapi
 * @param $api_number
 * @param $request_url
 * @param $request_data
 * @param $result
 */
function aptify_log_to_watchdog($api_number, $request_url, $request_data, $result) {
    $debug_mode = variable_get('aptify_api_debug', FALSE);
    if($debug_mode) {
        $txt  = "Web Service No: ".$api_number."\n";
        $txt .= "Path Sent to: \n";
        $txt .= $request_url."\n";
        $txt .= "Date Sent: \n";
        $txt .= var_dump($request_data)."\n";
        $txt .= "Data Received: \n";
        $txt .= $result."\n";
        $txt .= "---End of Log (".date("Y-m-d h-i-s").")---\n\n\n\n\n";
        watchdog(APTIFY_API_WATCHDOG, $txt, array(), WATCHDOG_INFO);
    }
}
